const GET_PRODUCT_DETAIL = "productDetail/GET_PRODUCT_DETAIL";
const SAVE_PRODUCT_DETAIL = "productDetail/SAVE_PRODUCT_DETAIL";

const GET_PRODUCT_VARIANTS = "productDetail/GET_PRODUCT_VARIANTS";
const SAVE_PRODUCT_VARIANTS = "productDetail/SAVE_PRODUCT_VARIANTS";

const SET_LOADING = "productDetail/SET_LOADING";
const SET_VARIANT_LOADING = "productDetail/SET_VARIANT_LOADING";

const SET_SELECTED_VARIANT = "productDetail/SET_SELECTED_VARIANT";

const CLEAR_PRODUCT_DETAIL = "productDetail/CLEAR_PRODUCT_DETAIL";

export {
  GET_PRODUCT_DETAIL,
  SAVE_PRODUCT_DETAIL,
  GET_PRODUCT_VARIANTS,
  SAVE_PRODUCT_VARIANTS,
  SET_LOADING,
  SET_VARIANT_LOADING,
  SET_SELECTED_VARIANT,
  CLEAR_PRODUCT_DETAIL,
};
