import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {Page,Table,Btn,Money} from '../components/UI';
import {orders} from '../api';
import {fmtDate} from '../utils/helpers';
const orderStatus=['pending','confirmed','processing','completed','cancelled','refunded'];
const paymentStatus=['pending','paid','failed','cancelled','refunded'];
const labels={pending:'Chờ xử lý',confirmed:'Đã xác nhận',processing:'Đang xử lý',completed:'Hoàn tất',cancelled:'Đã hủy',refunded:'Đã hoàn tiền'};
const payLabels={pending:'Chờ thanh toán',paid:'Đã thanh toán',failed:'Thanh toán lỗi',cancelled:'Đã hủy',refunded:'Đã hoàn tiền'};
export default function OrdersPage(){const [rows,setRows]=useState([]),[q,setQ]=useState(''),[os,setOs]=useState(''),[ps,setPs]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await orders.list({page:1,limit:100,...(os?{orderStatus:os}:{}),...(ps?{paymentStatus:ps}:{})});const d=r.data?.data??r.data;setRows(Array.isArray(d)?d:d?.data||[])}catch(e){setError(e.response?.data?.message||e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[os,ps]);
 const filtered=useMemo(()=>rows.filter(x=>!q||String(x.orderNumber||'').toLowerCase().includes(q.toLowerCase())||String(x.user?.name||'').toLowerCase().includes(q.toLowerCase())||String(x.user?.phone||'').includes(q)),[rows,q]);
 return <Page title="Đơn hàng" actions={<Btn onClick={load}>↻ Làm mới</Btn>}><div className="toolbar order-toolbar"><input placeholder="Tìm mã đơn, tên, SĐT…" value={q} onChange={e=>setQ(e.target.value)}/><select value={os} onChange={e=>setOs(e.target.value)}><option value="">Tất cả đơn hàng</option>{orderStatus.map(x=><option key={x} value={x}>{labels[x]}</option>)}</select><select value={ps} onChange={e=>setPs(e.target.value)}><option value="">Tất cả thanh toán</option>{paymentStatus.map(x=><option key={x} value={x}>{payLabels[x]}</option>)}</select></div>{error&&<div className="error">{error}</div>}<div className="order-summary"><div><span>Tổng đơn</span><b>{filtered.length}</b></div><div><span>Chờ xử lý</span><b>{filtered.filter(x=>x.orderStatus==='pending').length}</b></div><div><span>Đã thanh toán</span><b>{filtered.filter(x=>x.paymentStatus==='paid').length}</b></div><div><span>Doanh thu hiển thị</span><b><Money v={filtered.reduce((s,x)=>s+Number(x.total||0),0)}/></b></div></div><Table rows={filtered} columns={[{key:'orderNumber',label:'Mã đơn',render:r=><Link className="order-code" to={`/admin/orders/${r._id}`}>{r.orderNumber}</Link>},{key:'customer',label:'Khách hàng',render:r=><div><b>{r.customer?.fullName||r.user?.name||'—'}</b><small>{r.customer?.phone||r.user?.phone||r.user?.email||''}</small></div>},{key:'paymentMethod',label:'Thanh toán',render:r=><span className="soft-badge">{r.paymentMethod}</span>},{key:'paymentStatus',label:'TT',render:r=><span className={`status-pill ${r.paymentStatus}`}>{payLabels[r.paymentStatus]||r.paymentStatus}</span>},{key:'orderStatus',label:'Đơn hàng',render:r=><span className={`status-pill ${r.orderStatus}`}>{labels[r.orderStatus]||r.orderStatus}</span>},{key:'total',label:'Tổng tiền',render:r=><b><Money v={r.total}/></b>},{key:'createdAt',label:'Ngày',render:r=>fmtDate(r.createdAt)}]}/>{loading&&<p className="muted">Đang tải…</p>}</Page>}
