import{call,put,takeLatest}from'redux-saga/effects';import{auth,users,categories,brands,products,variants,addresses,carts,notifications,wishlists,orders,payments,reviews,coupons,orderItems}from'../api';import{one,unwrap,err}from'../utils/helpers';
const apis={users,categories,brands,products,variants,addresses,carts,notifications,wishlists,orders,payments,reviews,coupons,orderItems};
function* login(a){try{const r=yield call(auth.login,a.payload);const d=one(r);const token=d?.accessToken||d?.token||r.data?.accessToken||r.data?.token;const user=d?.user||d?.account||d;if(!['admin','manager','staff'].includes(user?.role))throw new Error('Tài khoản không có quyền truy cập trang quản trị');if(!token)throw new Error('Không nhận được access token');localStorage.setItem('adminToken',token);if(d?.refreshToken||r.data?.refreshToken)localStorage.setItem('refreshToken',d?.refreshToken||r.data?.refreshToken);localStorage.setItem('adminUser',JSON.stringify(user));localStorage.setItem('adminSessionExpiresAt',String(Date.now()+3*24*60*60*1000));yield put({type:'LOGIN_OK',payload:{token,user}})}catch(e){localStorage.removeItem('adminToken');localStorage.removeItem('adminUser');localStorage.removeItem('refreshToken');localStorage.removeItem('adminSessionExpiresAt');yield put({type:'LOGIN_ERR',payload:err(e)})}}
function* list(a){try{const r=yield call(apis[a.payload.resource].list,a.payload.params);yield put({type:'DATA_LIST_OK',payload:unwrap(r)})}catch(e){yield put({type:'DATA_LIST_ERR',payload:err(e)})}}
function* get(a){try{const r=yield call(apis[a.payload.resource].get,a.payload.id);yield put({type:'DATA_GET_OK',payload:one(r)})}catch(e){yield put({type:'DATA_ERR',payload:err(e)})}}
function* save(a){try{const {resource,id,data}=a.payload;const r=id?yield call(apis[resource].update,id,data):yield call(apis[resource].create,data);yield put({type:'DATA_OK',payload:one(r)})}catch(e){yield put({type:'DATA_ERR',payload:err(e)})}}
function* remove(a){try{yield call(apis[a.payload.resource].remove,a.payload.id);yield put({type:'DATA_OK',payload:null})}catch(e){yield put({type:'DATA_ERR',payload:err(e)})}}
function* logout(){try{const t=localStorage.getItem('refreshToken');yield call(auth.logout,{refreshToken:t||''})}catch{}localStorage.removeItem('adminToken');localStorage.removeItem('adminUser');localStorage.removeItem('refreshToken')}
export default function* rootSaga(){yield takeLatest('LOGIN_REQ',login);yield takeLatest('DATA_LIST_REQ',list);yield takeLatest('DATA_GET_REQ',get);yield takeLatest('DATA_REQ',save);yield takeLatest('DATA_DELETE_REQ',remove);yield takeLatest('LOGOUT',logout)}
