const r = require("express").Router();
r.use("/auth", require("./authRoutes"));
r.use("/users", require("./userRoutes"));
r.use("/addresses", require("./addressRoutes"));
r.use("/brands", require("./brandRoutes"));
r.use("/categories", require("./categoryRoutes"));
r.use("/products", require("./productRoutes"));
r.use("/variants", require("./productVariantRoutes"));
r.use("/cart", require("./cartRoutes"));
r.use("/coupons", require("./couponRoutes"));
r.use("/notifications", require("./notificationRoutes"));
r.use("/orders", require("./orderRoutes"));
r.use("/order-items", require("./orderItemRoutes"));
r.use("/payments", require("./paymentRoutes"));
r.use("/reviews", require("./reviewRoutes"));
r.use("/wishlist", require("./wishlistRoutes"));
r.use("/news", require("./newsRoutes"));
r.use("/news-categories", require("./newsCategoryRoutes"));
r.use("/banners", require("./bannerRoutes"));
r.use("/admin", require("./adminResourceRoutes"));
module.exports = r;
