import React, {useEffect,useState} from "react";import{useDispatch,useSelector}from'react-redux';import{Page,Table,Btn,Danger,Modal,Money}from'../components/UI';import{fmtDate,idOf}from'../utils/helpers';
import{users,categories,brands,addresses,coupons,orders,orderItems,payments,reviews,notifications,carts,wishlists}from'../api';
const configs={
 users:{title:'Người dùng',search:true,fields:[['name','Tên'],['email','Email'],['phone','Điện thoại'],['password','Mật khẩu'],['role','Role'],['status','Status']],cols:[['name','Tên'],['email','Email'],['role','Role'],['status','Trạng thái'],['phone','Điện thoại']]},
 categories:{title:'Danh mục',fields:[['name','Tên'],['slug','Slug'],['description','Mô tả'],['image','Ảnh'],['parent','Parent ID'],['level','Level'],['sortOrder','Sort'],['productCount','Số SP'],['status','Status']],cols:[['name','Tên'],['slug','Slug'],['level','Level'],['productCount','Số SP'],['status','Trạng thái']]},
 brands:{title:'Thương hiệu',fields:[['name','Tên'],['slug','Slug'],['logo','Logo'],['description','Mô tả'],['website','Website'],['sortOrder','Sort'],['status','Status']],cols:[['name','Tên'],['slug','Slug'],['website','Website'],['status','Trạng thái']]},
 addresses:{title:'Địa chỉ',admin:true,fields:[['user','User ID'],['fullName','Họ tên'],['phone','Điện thoại'],['province','Tỉnh/TP'],['district','Quận/Huyện'],['ward','Phường/Xã'],['address','Địa chỉ'],['note','Ghi chú'],['isDefault','Mặc định']],cols:[['fullName','Họ tên'],['phone','Điện thoại'],['province','Tỉnh'],['district','Huyện'],['ward','Phường'],['isDefault','Mặc định']]},
 coupons:{title:'Mã giảm giá',fields:[['code','Code'],['name','Tên'],['type','Type'],['value','Giá trị'],['minOrderValue','Đơn tối thiểu'],['maxDiscount','Giảm tối đa'],['usageLimit','Giới hạn'],['usageLimitPerUser','/ User'],['startDate','Bắt đầu'],['endDate','Kết thúc'],['status','Status']],cols:[['code','Code'],['name','Tên'],['type','Loại'],['value','Giá trị'],['startDate','Bắt đầu'],['endDate','Kết thúc'],['status','Trạng thái']]},
 orders:{title:'Đơn hàng',admin:true,fields:[['orderNumber','Mã đơn'],['user','User ID'],['paymentMethod','Thanh toán'],['paymentStatus','TT thanh toán'],['orderStatus','Trạng thái đơn'],['subtotal','Tạm tính'],['discount','Giảm giá'],['total','Tổng'],['note','Ghi chú']],cols:[['orderNumber','Mã đơn'],['paymentMethod','Thanh toán'],['paymentStatus','TT'],['orderStatus','Đơn hàng'],['total','Tổng'],['createdAt','Ngày']]},
 'order-items':{title:'Chi tiết đơn',fields:[['order','Order ID'],['product','Product ID'],['variant','Variant ID'],['productName','Tên SP'],['variantName','Tên Variant'],['sku','SKU'],['price','Giá'],['quantity','SL'],['discount','Giảm'],['total','Tổng']],cols:[['productName','Sản phẩm'],['variantName','Variant'],['sku','SKU'],['price','Giá'],['quantity','SL'],['total','Tổng']]},
 payments:{title:'Thanh toán',admin:true,fields:[['order','Order ID'],['user','User ID'],['method','Phương thức'],['amount','Số tiền'],['currency','Tiền tệ'],['status','Status'],['provider','Provider'],['transactionId','Transaction ID']],cols:[['order','Order'],['method','Phương thức'],['amount','Số tiền'],['status','Trạng thái'],['provider','Provider'],['createdAt','Ngày']]},
 reviews:{title:'Đánh giá',admin:true,fields:[['product','Product ID'],['user','User ID'],['order','Order ID'],['rating','Rating'],['title','Tiêu đề'],['content','Nội dung'],['verifiedPurchase','Đã mua'],['status','Status']],cols:[['rating','★'],['title','Tiêu đề'],['content','Nội dung'],['status','Trạng thái'],['verifiedPurchase','Đã mua']]},
 notifications:{title:'Thông báo',admin:true,fields:[['user','User ID'],['type','Type'],['title','Tiêu đề'],['message','Nội dung'],['data','Data JSON'],['isRead','Đã đọc']],cols:[['title','Tiêu đề'],['type','Type'],['isRead','Đã đọc'],['createdAt','Ngày']]},
 carts:{title:'Giỏ hàng',admin:true,fields:[['user','User ID'],['items','Items JSON']],cols:[['user','User'],['items','Items'],['createdAt','Ngày']]},
 wishlists:{title:'Yêu thích',admin:true,fields:[['user','User ID'],['products','Products JSON']],cols:[['user','User'],['products','Sản phẩm'],['createdAt','Ngày']]}
};
const base=(key,c)=>c.admin?`/admin/${key}`:`/${key}`;
const apiMap={users,categories,brands,addresses,coupons,orders,"order-items":orderItems,payments,reviews,notifications,carts,wishlists};
const dateKeys=new Set(["startDate","endDate"]);
const toInputDate=v=>v?new Date(v).toISOString().slice(0,16):"";
const fromInputDate=v=>v?v:new Date().toISOString();
export default function ResourcePage({resource}){const c=configs[resource];const d=useDispatch(),s=useSelector(x=>x.data),[open,setOpen]=useState(false),[id,setId]=useState(null),[f,setF]=useState({}),[q,setQ]=useState('');const load=()=>d({type:'DATA_LIST_REQ',payload:{resource,params:resource==='users'?{page:1,limit:100,search:q}:{page:1,limit:100}}});useEffect(()=>{load()},[resource]);const edit=async x=>{
  const entityId=x._id||x.id;
  setId(entityId);
  setOpen(true);
  try {
    const api=apiMap[resource];
    const r=api?.get?await api.get(entityId):null;
    const z=r?(r.data?.data??r.data):x;
    if(resource==='notifications'&&z.data)z.data=JSON.stringify(z.data);
    if(['carts','wishlists'].includes(resource)){z.items=z.items?JSON.stringify(z.items):'';z.products=z.products?JSON.stringify(z.products):'';}
    for(const k of dateKeys) if(z[k]) z[k]=toInputDate(z[k]);
    setF(z);
  } catch(e) {
    const z={...x};
    if(resource==='notifications'&&z.data)z.data=JSON.stringify(z.data);
    if(['carts','wishlists'].includes(resource)){z.items=z.items?JSON.stringify(z.items):'';z.products=z.products?JSON.stringify(z.products):'';}
    for(const k of dateKeys) if(z[k]) z[k]=toInputDate(z[k]);
    setF(z);
  }
};const add=()=>{setId(null);setF({});setOpen(true)};const val=(k,v)=>{if(dateKeys.has(k))return fromInputDate(v);if(['data','items','products'].includes(k)){try{return JSON.parse(v||'[]')}catch{return{}}}if(['isDefault','isRead','verifiedPurchase'].includes(k))return v==='true'||v===true;if(['level','sortOrder','productCount','value','minOrderValue','maxDiscount','usageLimit','usageLimitPerUser','rating','subtotal','discount','total','amount','price','quantity'].includes(k))return Number(v)||0;return v};const save=()=>{const data={};for(const [k] of c.fields)data[k]=val(k,f[k]);d({type:'DATA_REQ',payload:{resource,id,data}});setOpen(false);setTimeout(load,450)};const del=x=>{if(confirm('Xóa dữ liệu này?')){d({type:'DATA_DELETE_REQ',payload:{resource,id:x._id}});setTimeout(load,400)}};return <Page title={c.title} actions={<Btn onClick={add}>+ Thêm</Btn>}><div className="toolbar">{c.search&&<><input placeholder="Tìm kiếm…" value={q} onChange={e=>setQ(e.target.value)}/><Btn onClick={load}>Tìm</Btn></>}</div><Table rows={s.items} columns={[...c.cols.map(([k,l])=>({key:k,label:l,render:r=>k==='total'||k==='amount'||k==='price'?<Money v={r[k]}/>:k==='createdAt'?fmtDate(r[k]):typeof r[k]==='object'?idOf(r[k])||JSON.stringify(r[k]).slice(0,80):String(r[k]??'—')})),{key:'actions',label:'Thao tác',render:r=><span className="actions"><Btn onClick={()=>edit(r)}>Sửa</Btn><Danger onClick={()=>del(r)}>Xóa</Danger></span>}]}/>{open&&<Modal title={id?'Sửa':'Thêm'} onClose={()=>setOpen(false)}><div className="formgrid">{c.fields.map(([k,l])=><label key={k}>{l}{dateKeys.has(k)?<input type="datetime-local" value={f[k]??''} onChange={e=>setF({...f,[k]:e.target.value})}/>:k==='status'?<select value={f[k]??'active'} onChange={e=>setF({...f,[k]:e.target.value})}><option value="active">active</option><option value="inactive">inactive</option><option value="pending">pending</option><option value="approved">approved</option><option value="cancelled">cancelled</option><option value="paid">paid</option></select>:k==='type'&&resource==='coupons'?<select value={f[k]??'percentage'} onChange={e=>setF({...f,[k]:e.target.value})}><option value="percentage">percentage</option><option value="fixed">fixed</option></select>:['isDefault','isRead','verifiedPurchase'].includes(k)?<select value={String(f[k]??false)} onChange={e=>setF({...f,[k]:e.target.value})}><option value="false">false</option><option value="true">true</option></select>:<input value={typeof f[k]==='object'?JSON.stringify(f[k]):f[k]??''} onChange={e=>setF({...f,[k]:e.target.value})}/>}</label>)}<div className="full"><Btn onClick={save}>Lưu</Btn></div></div></Modal>}</Page>}
