import React, { useEffect, useState } from "react";
import { Link, Navigate, useNavigate, useParams } from "react-router-dom";
import * as api from "../../api/shop";
import { attributesOf, cartTotal, imageOf, money, unwrapList } from "../../utils/shop";

const errorText = (e) => e?.response?.data?.message || "Không thể thực hiện thao tác";
const blankAddress = { fullName: "", phone: "", address: "", province: "", district: "", ward: "", note: "" };
const statusLabel = { pending: "Chờ xác nhận", confirmed: "Đã xác nhận", processing: "Đang xử lý", completed: "Hoàn tất", cancelled: "Đã hủy", refunded: "Đã hoàn tiền" };

export function CartPage() {
  const [cart, setCart] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const load = async () => { try { setCart(await api.getCart()); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const update = async (id, quantity) => { if (quantity < 1) return; setBusy(id); try { await api.updateCartItem(id, quantity); await load(); window.dispatchEvent(new Event("cart-change")); } catch (e) { setError(errorText(e)); } finally { setBusy(""); } };
  const remove = async (id) => { setBusy(id); try { await api.removeCartItem(id); await load(); window.dispatchEvent(new Event("cart-change")); } catch (e) { setError(errorText(e)); } finally { setBusy(""); } };
  const clear = async () => { if (!window.confirm("Xóa toàn bộ sản phẩm trong giỏ?")) return; try { await api.clearCart(); await load(); window.dispatchEvent(new Event("cart-change")); } catch (e) { setError(errorText(e)); } };
  if (loading) return <div className="state">Đang tải giỏ hàng...</div>;
  const items = cart?.items || [];
  if (!items.length) return <div className="empty large"><h1>Giỏ hàng đang trống</h1><p>Hãy chọn thêm vài sản phẩm bạn yêu thích.</p><Link className="primary-button" to="/products">Tiếp tục mua sắm</Link></div>;
  return <section><div className="section-heading"><div><p className="eyebrow">SHOPPING BAG</p><h1>Giỏ hàng của bạn</h1></div><button className="link-button danger" onClick={clear}>Xóa tất cả</button></div>{error && <div className="form-error">{error}</div>}<div className="cart-layout"><div className="cart-items">{items.map((item) => <article className="cart-item" key={item._id}><img src={imageOf(item)} alt={item.product?.name || "Sản phẩm"} /><div className="cart-item-copy"><Link to={`/products/${item.product?._id}`}><h3>{item.product?.name || "Sản phẩm"}</h3></Link><p>{attributesOf(item.attributes || item.variant?.attributes).map(([k, v]) => `${k}: ${v}`).join(" · ")}</p><b>{money(item.price)}</b></div><div className="quantity"><button disabled={!!busy} onClick={() => update(item._id, item.quantity - 1)}>−</button><span>{busy === item._id ? "…" : item.quantity}</span><button disabled={!!busy} onClick={() => update(item._id, item.quantity + 1)}>+</button></div><button className="remove-button" disabled={!!busy} onClick={() => remove(item._id)}>×</button></article>)}</div><aside className="summary"><h2>Tóm tắt đơn hàng</h2><div><span>Tạm tính</span><b>{money(cartTotal(cart))}</b></div><div><span>Phí vận chuyển</span><span>Chưa tính</span></div><p className="muted">Liên hệ <Link to="/contact">Hoa Sen</Link> để xác nhận phí giao hàng trước khi đặt.</p><hr /><div className="summary-total"><span>Tạm tính đơn hàng</span><b>{money(cartTotal(cart))}</b></div><Link className="primary-button full" to="/checkout">Tiến hành thanh toán</Link></aside></div></section>;
}

export function CheckoutPage() {
  const [cart, setCart] = useState(null); const [addresses, setAddresses] = useState([]); const [addressId, setAddressId] = useState(""); const [form, setForm] = useState(blankAddress); const [paymentMethod, setPaymentMethod] = useState("cod"); const [couponCode, setCouponCode] = useState(""); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const navigate = useNavigate();
  useEffect(() => { Promise.all([api.getCart(), api.getAddresses()]).then(([nextCart, nextAddresses]) => { setCart(nextCart); const list = unwrapList(nextAddresses); setAddresses(list); const defaultAddress = list.find((x) => x.isDefault) || list[0]; if (defaultAddress) setAddressId(defaultAddress._id); }).catch((e) => setError(errorText(e))); }, []);
  const submit = async (e) => { e.preventDefault(); setSaving(true); setError(""); try { let chosen = addressId; if (!chosen) chosen = (await api.createAddress(form))._id; await api.createOrder({ addressId: chosen, paymentMethod, couponCode: couponCode.trim() || undefined, note: note.trim() || undefined }); window.dispatchEvent(new Event("cart-change")); navigate("/orders"); } catch (e) { setError(errorText(e)); } finally { setSaving(false); } };
  if (!cart?.items?.length) return <Navigate to="/cart" replace />;
  return <section><div className="section-heading"><div><p className="eyebrow">CHECKOUT</p><h1>Thanh toán</h1></div><Link to="/cart">← Quay lại giỏ hàng</Link></div><form className="checkout-layout" onSubmit={submit}><div className="checkout-card"><h2>Địa chỉ nhận hàng</h2>{addresses.length > 0 && <select value={addressId} onChange={(e) => setAddressId(e.target.value)}><option value="">+ Nhập địa chỉ mới</option>{addresses.map((a) => <option key={a._id} value={a._id}>{a.fullName} · {a.phone} · {a.address}</option>)}</select>}{!addressId && <div className="address-fields">{[["fullName","Họ và tên"],["phone","Số điện thoại"],["address","Địa chỉ cụ thể"],["province","Tỉnh / Thành phố"],["district","Quận / Huyện"],["ward","Phường / Xã"]].map(([key, label]) => <input key={key} required placeholder={label} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} />)}</div>}<label className="field-label">Ghi chú đơn hàng<textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Ví dụ: giao giờ hành chính" /></label><h2>Phương thức thanh toán</h2>{[["cod","Thanh toán khi nhận hàng (COD)"],["bank_transfer","Chuyển khoản ngân hàng"],["vnpay","Thanh toán VNPAY"]].map(([value, label]) => <label className="payment-option" key={value}><input type="radio" checked={paymentMethod === value} onChange={() => setPaymentMethod(value)} /> {label}</label>)}<label className="field-label">Mã giảm giá<input value={couponCode} onChange={(e) => setCouponCode(e.target.value.toUpperCase())} placeholder="Nhập mã coupon nếu có" /></label>{error && <div className="form-error">{error}</div>}</div><aside className="summary"><h2>Đơn hàng</h2>{cart.items.map((item) => <div key={item._id}><span>{item.product?.name} × {item.quantity}</span><b>{money(item.price * item.quantity)}</b></div>)}<p className="muted">Phí vận chuyển chưa tính trong tổng này. <Link to="/contact">Liên hệ để xác nhận</Link>.</p><hr /><div className="summary-total"><span>Tạm tính đơn hàng</span><b>{money(cartTotal(cart))}</b></div><button className="primary-button full" disabled={saving}>{saving ? "Đang tạo đơn..." : "Đặt hàng"}</button></aside></form></section>;
}

export function OrdersPage() {
  const [orders, setOrders] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { try { setOrders(unwrapList(await api.getOrders({ page: 1, limit: 50 }))); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const cancel = async (id) => { if (!window.confirm("Bạn chắc chắn muốn hủy đơn hàng?")) return; try { await api.cancelOrder(id); await load(); } catch (e) { setError(errorText(e)); } };
  if (loading) return <div className="state">Đang tải đơn hàng...</div>;
  return <section><p className="eyebrow">MY ACCOUNT</p><h1>Đơn hàng của tôi</h1>{error && <div className="form-error">{error}</div>}{orders.length ? <div className="orders-list">{orders.map((order) => <div className="order-card" key={order._id}><Link to={`/orders/${order._id}`}><b>{order.orderNumber}</b><p>{new Date(order.createdAt).toLocaleDateString("vi-VN")} · {order.paymentMethod}</p></Link><div><strong>{money(order.total)}</strong><span className="status">{statusLabel[order.orderStatus] || order.orderStatus}</span>{["pending","confirmed"].includes(order.orderStatus) && <button className="link-button danger" onClick={() => cancel(order._id)}>Hủy đơn</button>}</div></div>)}</div> : <div className="empty"><h3>Bạn chưa có đơn hàng</h3><Link to="/products">Bắt đầu mua sắm →</Link></div>}</section>;
}

export function OrderDetailPage() {
  const { id } = useParams(); const [state, setState] = useState({ loading: true, data: null, error: "" });
  useEffect(() => { api.getOrder(id).then((data) => setState({ loading: false, data, error: "" })).catch((e) => setState({ loading: false, data: null, error: errorText(e) })); }, [id]);
  if (state.loading) return <div className="state">Đang tải chi tiết đơn...</div>; if (state.error) return <div className="state error">{state.error}</div>; const { order, items } = state.data;
  return <section><Link to="/orders">← Quay lại đơn hàng</Link><div className="detail-order"><p className="eyebrow">{order.orderNumber}</p><h1>Chi tiết đơn hàng</h1><p>Trạng thái: <span className="status">{statusLabel[order.orderStatus] || order.orderStatus}</span></p><div className="order-address"><b>Giao đến</b><p>{order.customer?.fullName} · {order.customer?.phone}</p><p>{order.address?.address}, {order.address?.ward}, {order.address?.district}, {order.address?.province}</p></div>{items.map((item) => <div className="order-line" key={item._id}><img src={imageOf(item)} alt={item.productName} /><span>{item.productName}<small>{item.variantName} · SL: {item.quantity}</small></span><b>{money(item.total)}</b></div>)}<div className="summary-total"><span>Tổng cộng</span><b>{money(order.total)}</b></div></div></section>;
}
