const mongoose = require("mongoose");
const schema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    nameEn: { type: String, trim: true, default: "" },
    slug: {
      type: String,
      required: true,
      unique: true,
      index: true,
      lowercase: true,
    },
    description: String,
    descriptionEn: { type: String, default: "" },
    shortDescription: String,
    shortDescriptionEn: { type: String, default: "" },
    sku: { type: String, unique: true, sparse: true, trim: true },
    barcode: String,
    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Category",
      required: true,
    },
    brand: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Brand",
      default: null,
    },
    images: [String],
    thumbnail: String,
    video: String,
    attributes: { type: Map, of: [String], default: {} },
    attributeTranslations: [{
      name: { type: String, required: true },
      nameEn: { type: String, default: "" },
      values: [{ value: { type: String, required: true }, valueEn: { type: String, default: "" } }],
    }],
    hasVariants: { type: Boolean, default: false },
    weight: Number,
    weightUnit: { type: String, default: "g" },
    dimensions: { length: Number, width: Number, height: Number },
    status: {
      type: String,
      enum: ["draft", "active", "inactive", "archived", "out_of_stock"],
      default: "draft",
    },
    featured: { type: Boolean, default: false },
    isNew: { type: Boolean, default: true },
    isBestSeller: { type: Boolean, default: false },
    isOnSale: { type: Boolean, default: false },
    metaTitle: String,
    metaDescription: String,
    metaKeywords: [String],
    ratingAverage: { type: Number, default: 0 },
    ratingCount: { type: Number, default: 0 },
    soldCount: { type: Number, default: 0 },
    viewCount: { type: Number, default: 0 },
    favoriteCount: { type: Number, default: 0 },
    publishedAt: Date,
  },
  { timestamps: true },
);
module.exports = mongoose.model("Product", schema);
